### ISSUE TITLE
Suggestion: Change default matching algorithm

### ISSUE THREAD

**Issue by BenjaminWaye** [andrelandgraf/react-datalist-input#22]
It seems the default matching functionality is not as expected from a datalist. Without the same matching algorithm as the datalist this component doesn't provide the expected value. What I believe most people are looking for is a datalist functioning component with onSelect which is the current issue with using the html tag

**Comment by BenjaminWaye** [comment]
This seems to be a good solution 

const match = (currentInput, item) => {
      return (item.label.toLowerCase().includes(currentInput.toLowerCase()))
    }

**Comment by andrelandgraf** [comment]
Hey, thanks for the feedback. That's a good point, it's always good to stay consistent. 

```javascript
match = (currentInput, item) => {
  return (
    item.label.substr(0, currentInput.length).toUpperCase() ===
    currentInput.toUpperCase()
  );
};
```

I used a matching algorithm similar to [startsWith](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith) to support common drop down use cases like language selection, country selection and so on. 

I will definitely keep it in mind, maybe if it comes up more often, I could change the default matching. But keep in mind that would not be backwards compatible and would require a major release. 

Luckily, you are free to choose whatever matching you need by just [passing a callback func](https://www.npmjs.com/package/react-datalist-input#markdown-header-match) to the component. Also, the package is well documented so I hope you weren't too confused.

**Comment by BenjaminWaye** [comment]
Thanks for your nice comment! Maybe it would be worth it to add the
matching algo to docs?

Den lör 14 nov. 2020 13:06Andre <notifications@github.com> skrev:

**Comment by andrelandgraf** [comment]
Done 👍

**Comment by emilwallgren** [comment]
Hi, great tool Andre!
If I understand it correctly, the above issue corresponds with a current issue of mine as well.

For example, If i have a list of fruits (where Banana exists), then typing in anana wont give me a match as a regular datalist would. Of course my application isn't that simple but instead uses this package to list urls and search queries in Google where I would like to match on a sub-string.

Is there a fix for this? Can't find it clearly.
If there isn't, then maybe I can help to fix it?

I saw your comment above:
> Changing the default matching would not be backwards compatible and would require a major release. But I will definitely keep it in mind, maybe if it comes up more often, I could change the default matching.

If the above is the case, how about we develop this together if it's a great deal of work? :)

> Do you know that you can [pass a callback function](https://www.npmjs.com/package/react-datalist-input#markdown-header-match) to the react-datalist-input component to implement the matching algorithm of your choice? I think the matching is well documented on the README, so I hope you weren't too confused.

That link doesn't lead anywhere :)

**Comment by andrelandgraf** [comment]
Hi @emilwallgren,

Thanks! You are right, the default filtering function right now is `startsWithValue`. This changed with my recent rewrite (version 3.0.0) and was most likely a slip on my side. I definitely want to make sure to stay consistent with the default datalist HTML element behavior and use `includes` as the default. So thanks for reaching out and letting me know!

Please update to version `3.1.0` which now uses `includes` as the default filter. 

But also a heads-up. You can always change the filtering of this component. Please have a look at the most recent documentation on [how to change the filter](https://github.com/andrelandgraf/react-datalist-input#filtering). Hence, even without upgrading, you would be able to update the filtering algorithm in your code.

**Comment by emilwallgren** [comment]
You my main man, is awesome!

Just updated on my end (worked straight out of the box) and saved me hours of work here!
Thanks for being a great developer :)
