### ISSUE TITLE
Unable to select the same value again after clearing

### ISSUE THREAD

**Issue by sajidfrommerqata** [andrelandgraf/react-datalist-input#25]
Usually, the plugin is working but if I do like this then it's not working. Can you let me know how I can manage this?

1. When I select a value and store it in a variable through OnSelect 
2. Then I clear the variable which has the value through another button 
3. Then again when I want to select the same value from the dropdown it's not selecting. I can select other values but which I used before.

**Comment by andrelandgraf** [comment]
Hey @sajidfrommerqata, 

By default re-select will be suppressed. This was a early-stage design decision. You can set the prop [suppressReselect](https://www.npmjs.com/package/react-datalist-input#markdown-header-suppressReselect) to false to change that behaviour. 

It's documented in the README. Let me know if that works!

**Comment by sajidfrommerqata** [comment]
it's working. thank you for your help@andrelandgraf
