### ISSUE TITLE
Add debounce option?

### ISSUE THREAD

**Issue by uncleramsay** [andrelandgraf/react-datalist-input#4]
Thanks so much for this package, I love it!

I was wondering if it would be possible to add an option to debounce the matching algorithm.
In my use case I have a relatively large number of items, and a not-insignificant matching algorithm. As a result, if I type too much too quickly, the computer starts to lag a little while it catches up. If I could debounce the match calls it should significantly improve performance.

Thanks!

**Comment by andrelandgraf** [comment]
Thanks, happy to hear! 

I implemented an option to debounce the matching algorithm and published the new version on npm, see README for more information. I tested the option with around 14k items and some heavier matching algorithms (see `testing/demo-app`) and especially the loading feedback felt like it would improve the overall experience. 

As mentioned in the README, if it still feels laggy, consider implementing a normal search-bar with a "search"-button or something similar to literally debounce the matching algorithm from user input. 

Feel free to provide further feedback!
