### ISSUE TITLE
Something wrong with webpack in the 3.1.0 version

### ISSUE THREAD

**Issue by mikechen-dev** [andrelandgraf/react-datalist-input#52]
Hi, I got the same error both on react and next.js project when I try to put this in jsx block
Any suggestion to solve this? Thanks
`<DatalistInput
    placeholder="Chocolate"
    label="Select ice cream flavor"
    onSelect={(item) => console.log(item.value)}
    items={[
      { id: 'Chocolate', value: 'Chocolate' },
      { id: 'Coconut', value: 'Coconut' },
      { id: 'Mint', value: 'Mint' },
      { id: 'Strawberry', value: 'Strawberry' },
      { id: 'Vanilla', value: 'Vanilla' },
    ]}
  />`
  <img width="966" alt="截圖 2022-09-23 下午2 35 43" src="https://user-images.githubusercontent.com/103172121/191904963-062600ea-7a2f-4461-9ef1-2131302925b4.png">

**Comment by andrelandgraf** [comment]
Hi @mikechen-dev, 

The error reads to me like you are not on React 18 but an earlier version of React. The latest versions of this package, starting with v3, take advantage of React 18 (React 18 added new hooks like `useId`).

Check out the [Installation section](https://github.com/andrelandgraf/react-datalist-input#installation) of the README. It should help you determine which version to use:

> Note: React 18 required! Version 3.0.0 utilizes React 18. If you use React <=17, install react-datalist-input@2.2.1 instead! Find the documentation for version 2.2.1 [here](https://github.com/andrelandgraf/react-datalist-input/blob/bab05504c0dffa5f9343f2fcb5f075a38bad2512/README.md).
