### ISSUE TITLE
Using the `name` prop for the input

### ISSUE THREAD

**Issue by mechmillan** [andrelandgraf/react-datalist-input#55]
I'd like to use this component as part of a form that gets submitted - I have some validations that will enforce that this field is required but I am not seeing how I can use this input in the form. The `inputProps` accepts `name` but it is not being picked up by the form. 

Is this possible with this library? I am using Yup + Formik for the form. Thank you!

**Comment by andrelandgraf** [comment]
Let me have a look later today. `inputProps` should pass the name down to the input field. Is this a runtime issue or is TypeScript complaining?

**Comment by andrelandgraf** [comment]
Hi @mechmillan, just double-checked. 

You can pass `name` to the `inputProps` property:

```
<DatalistInput
          label="Select your favorite flavor"
          placeholder="Chocolate"
          items={items}
          onSelect={(i) => console.log(i)}
          inputProps={{
            onClick: (e) => console.log('CLICK', e),
            name: 'flavor',
          }}
        />
```

It's just a input, so it should be picked up by the form as long as it is inside the form. If you still have issues, just share some code. Happy to help!

**Comment by mechmillan** [comment]
Thank you for the input! The name property was being picked up properly but I was missing the `onChange` and `value` props to tie the input in to Formik. 

For reference, here is how I got the field working (the `handleChange`, `values`, `setFieldValue`, and `setFieldTouched` come from the `useFormik` hook) :

```ts
<DatalistInput
          label="subject"
          inputProps={{
            name: 'subject',
            onChange: handleChange,
            value: values.subject,
          }}
          onSelect={async (item) => {
            await setFieldTouched('subject');
            await setFieldValue('subject', item.value);
          }}
          showLabel={false}
          items={localSubjectLines.map((subjectLine) => ({ id: subjectLine, value: subjectLine }))}
        />
```

**Comment by andrelandgraf** [comment]
I see. I should type that better, thanks for pointing out the issue!

`onChange` and `value` are orchestrated on the `DatalistInput` level. Just move them out of the `inputProps` and it should work!

You can find an example [here](https://github.com/andrelandgraf/react-datalist-input#fine-grained-control-vol-2---multi-select).
