### ISSUE TITLE
Highlighted <span> returns wrong substring

### ISSUE THREAD

**Issue by noe-david** [andrelandgraf/react-datalist-input#62]
Function `Highlight` returns the wrong string when `<span>` is used.

Now: `<span {...props}>{children.substring(index, inputLength)}</span>`
Should be: `<span {...props}>{children.substring(index, index + inputLength)}</span>`

**Comment by andrelandgraf** [comment]
Thanks for the heads-up! Fixed and published as `3.2.1`.
