### ISSUE TITLE
how show dropdown lists only after starting to type, i don't want to show all the suggestions even before start typing

### ISSUE THREAD

**Issue by mmestiyak** [andrelandgraf/react-datalist-input#69]
i'm just focusing on the input, and immediately it's showing the dropdown list but i want to show only when user start to type not just focus, i saw `isExpanded & setExpanded` props from the hook provided by the library, it works very fine but when i focus/click on input it doesn't work, i tried to setExpanded(false) on click to input, but it appears the list like a nano second, help please

**Comment by andrelandgraf** [comment]
Hey! That's an interesting edge case.

You can use a custom filter function that returns an empty array anytime the current input is empty:

```jsx
import { DatalistInput, useComboboxControls, includesValueFilter } from 'react-datalist-input';

const { setValue, value } = useComboboxControls({ isExpanded: false });

<DatalistInput
    label="Select ice cream flavor"
    value={value}
    setValue={setValue}
    filters={[(items) => (value ? items : []), includesValueFilter]}
    items={items} />
```

I would need to look into the accessibility guidelines to see how I could update the package to better support your use case using the `isExpanded` prop. Currently, the internal code updates `isExpanded` on focus.

Hope this helps!

**Comment by mmestiyak** [comment]
Thank you so much for the blazing-fast reply, it's working smoothly, I would like to look into this and contribute if I get to manage time.
