### ISSUE TITLE
Better handling of large result sets

### ISSUE THREAD

**Issue by uncleramsay** [andrelandgraf/react-datalist-input#7]
Hi,

I love this package! Thanks so much for putting it together.

One issue I have is that with a very large result set with many similarly-titled items it becomes difficult to find what you are looking for.

I can't allow all the results to show because the rendering is far too slow, so I use dropdownLength to limit it. But with a limited result set it's not easy for the user to see that there might be more options they are missing.

Would it be possible to put a final option on the list saying 'n more results available', or better still, an option to 'load n more results', so that the user can incrementally render more results as needed?

Hope that all makes sense!

**Comment by andrelandgraf** [comment]
Hi, 

I like the idea and will think about a pluggable solution. Unfortunately, I am currently moving and this will need some time, so maybe fork and try it out yourself?
